filler2: comments and some final touches
* added appropriate copyright notes
* added "not implemented" message for option '-u' in szb2filler
* some comments for remarks part.

diff --git a/qt4/filler2/szb2filler b/qt4/filler2/szb2filler
--- a/qt4/filler2/szb2filler
+++ b/qt4/filler2/szb2filler
@@ -18,6 +18,7 @@
 # MA  02110-1301, USA
 #
 # Author: Tomasz Pieczerak <tph AT newterm.pl>
+# Copyright (C) 2014-2015 Newterm
 
 VERSION="1.0"
 
@@ -163,6 +164,7 @@ case $ACTION in
 	unset-current)
 		# unset permissions for files from current month
 		# TODO
-		exit 0
+		echo "`basename $0`: error: option not implemented" 1>&2
+		exit 1
 		;;
 esac
