parstart: prevent from restart if i2smo fails
+ parstart won't restart if i2smo (ipk2szarp) fail to check IPK
  configuration
+ stop and start commands still work like previous

diff --git a/resources/parstart_TEMPLATE b/resources/parstart_TEMPLATE
--- a/resources/parstart_TEMPLATE
+++ b/resources/parstart_TEMPLATE
@@ -236,6 +236,11 @@ case "$1" in
 
 	;;
   restart|reload)
+	if [ -x __INSTALL_DIR__/bin/ipk2szarp ]; then
+		echo "Verifying configuration: __INSTALL_DIR__/ipk2szarp"
+		__INSTALL_DIR__/bin/ipk2szarp || { echo "Invalid configuration -- won't restart" 1>&2; exit 1; }
+	fi
+
 	$0 stop
 	$0 start
 	;;
