Stop overwriting apache config in szarp-xsltd

diff --git a/debian/szarp-xsltd.postinst b/debian/szarp-xsltd.postinst
--- a/debian/szarp-xsltd.postinst
+++ b/debian/szarp-xsltd.postinst
@@ -3,18 +3,22 @@
 
 set -e;
 
-. /usr/share/debconf/confmodule;
+# Stolen from libapache2-mod-wsgi
+apache_force_reload() {
+    if apache2ctl configtest 2>/dev/null; then
+        #invoke-rc.d apache2 force-reload || true
+        # use "restart" as a workaround for bug #558608
+        invoke-rc.d apache2 restart || true
+    else
+        echo "Your apache2 configuration is broken, please fix it and restart apache2 manually."
+    fi
+}
+
 
 case "$1" in
     configure)
 
 	[ -d /etc/apache2/sites-available ] || exit 0
-	[ -x /etc/init.d/apache2 ] && {
-		/etc/init.d/apache2 stop
-	}
-	
-	ln -sf /opt/szarp/resources/xsltd/apache2-szarp \
-		/etc/apache2/sites-available/szarp
 
 	[ -x /usr/sbin/a2enmod ] && {
 		[ -e /etc/apache2/mods-available/mod_python.load ] && /usr/sbin/a2enmod mod_python
@@ -23,14 +27,21 @@ case "$1" in
 		/usr/sbin/a2enmod rewrite
 	}
 
-	[ -x /usr/sbin/a2ensite ] && {
-		/usr/sbin/a2ensite szarp
+
+	# Upgrade fails becouse old prerm deletes config
+	[ ! -e /etc/apache2/sites-available/szarp ] && {
+		cp /opt/szarp/resources/xsltd/apache2-szarp /etc/apache2/sites-available/szarp
 	}
+
+	# Replace config only when is not changed by user
+	ucf /opt/szarp/resources/xsltd/apache2-szarp /etc/apache2/sites-available/szarp 
+	ucfr szarp-xsltd /etc/apache2/sites-available/szarp
+
+	[ -e /etc/apache2/sites-available/szarp ] && {
+		[ -x /usr/sbin/a2ensite ] &&  /usr/sbin/a2ensite szarp
 	
-	[ -x /etc/init.d/apache2 ] && {
-		/etc/init.d/apache2 start
+		apache_force_reload
 	}
-	
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
@@ -46,8 +57,6 @@ esac
 # generated by other debhelper scripts.
 
 #DEBHELPER#
-
-db_stop;
 
 exit 0
 
